smoke test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -77,8 +77,19 @@ jobs:
     runs-on: ubuntu-latest
     needs: docker
     steps:
+      - uses: azure/login@v2
+        with:
+          creds: ${{ secrets.AZURE }}
       - uses: azure/webapps-deploy@v3
         with:
           app-name: murbaniak-api-test
           images: ghcr.io/murbaniak25/course-gh-actions/api:latest
-          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A5A4D7A7A5D745D3B8D7BF57E0CB14F6 }}
+      - name: Smoke test
+        run: |
+          sleep 10
+          curl -f https://murbaniak-api-test-staging.azurewebsites.net/health || exit 1
+
+      - name: Rollback on failure
+        if: failure()
+        run: |
+          echo "Deployment failed, rolling back to previous version..."
